### ISSUE TITLE
hangs inside gstreamer

### ISSUE THREAD

**Issue by drzraf** [innir/gtranscribe#8]
```
#0  0x00007fe34d66fc68 in g_object_unref () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007fe34d692394 in g_value_reset () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007fe344a62dcb in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#3  0x00007fe344a62c79 in gst_iterator_next () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#4  0x00007fe344a630b7 in gst_iterator_fold () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#5  0x00007fe344a2dfdb in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#6  0x00007fe344a34024 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#7  0x00007fe344a554b8 in gst_element_query () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#8  0x00007fe344a2dd78 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#9  0x00007fe344a630fc in gst_iterator_fold () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#10 0x00007fe344a2dfdb in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#11 0x00007fe344a34024 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#12 0x00007fe344a554b8 in gst_element_query () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#13 0x00007fe344aabd31 in gst_element_query_position () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#14 0x00007fe34d139038 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#15 0x00007fe34d138a9a in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#16 0x00007fe34dd4e9cc in ?? () from /usr/lib/python3/dist-packages/gi/_gi.cpython-35m-x86_64-linux-gnu.so
#17 0x00007fe34dd50478 in ?? () from /usr/lib/python3/dist-packages/gi/_gi.cpython-35m-x86_64-linux-gnu.so
#18 0x00007fe34dd44209 in ?? () from /usr/lib/python3/dist-packages/gi/_gi.cpython-35m-x86_64-linux-gnu.so
#19 0x00005622cf563647 in PyObject_Call ()
#20 0x00005622cf4daee1 in PyEval_EvalFrameEx ()
#21 0x00005622cf4e00df in PyEval_EvalCodeEx ()
#22 0x00005622cf51c5d3 in ?? ()
#23 0x00005622cf563647 in PyObject_Call ()
#24 0x00005622cf51ebfe in ?? ()
#25 0x00005622cf543f2d in _PyObject_GenericGetAttrWithDict ()
#26 0x00005622cf4d6159 in PyEval_EvalFrameEx ()
#27 0x00005622cf4e00df in PyEval_EvalCodeEx ()
#28 0x00005622cf51c648 in ?? ()
#29 0x00005622cf563647 in PyObject_Call ()
#30 0x00005622cf48394e in ?? ()
#31 0x00005622cf563647 in PyObject_Call ()
#32 0x00005622cf516e30 in PyEval_CallObjectWithKeywords ()
#33 0x00007fe34dd4c42c in ?? () from /usr/lib/python3/dist-packages/gi/_gi.cpython-35m-x86_64-linux-gnu.so
#34 0x00007fe34d138e2f in ffi_closure_unix64_inner () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#35 0x00007fe34d1391a0 in ffi_closure_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#36 0x00007fe34d38d6aa in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007fe34d38da60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007fe34d38dd82 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007fe346838d55 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#40 0x00007fe34d139038 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#41 0x00007fe34d138a9a in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#42 0x00007fe34dd4e9cc in ?? () from /usr/lib/python3/dist-packages/gi/_gi.cpython-35m-x86_64-linux-gnu.so
#43 0x00007fe34dd50478 in ?? () from /usr/lib/python3/dist-packages/gi/_gi.cpython-35m-x86_64-linux-gnu.so
#44 0x00005622cf563647 in PyObject_Call ()
#45 0x00005622cf4daee1 in PyEval_EvalFrameEx ()
#46 0x00005622cf4da93f in PyEval_EvalFrameEx ()
#47 0x00005622cf4df286 in ?? ()
#48 0x00005622cf4dff9f in PyEval_EvalCode ()
#49 0x00005622cf5ad8f2 in ?? ()
#50 0x00005622cf5afe1d in PyRun_FileExFlags ()
#51 0x00005622cf5b05be in PyRun_SimpleFileExFlags ()
#52 0x00005622cf5de4d7 in Py_Main ()
#53 0x00005622cf46ec01 in main ()
```

keeping it running then bt again:

```
#0  0x00007fe3507e87ce in pthread_cond_signal@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00005622cf4d5bdc in ?? ()
#2  0x00005622cf4d5d0b in PyEval_SaveThread ()
#3  0x00007fe34dd4e9ad in ?? () from /usr/lib/python3/dist-packages/gi/_gi.cpython-35m-x86_64-linux-gnu.so
#4  0x00007fe34dd50478 in ?? () from /usr/lib/python3/dist-packages/gi/_gi.cpython-35m-x86_64-linux-gnu.so
#5  0x00007fe34dd44209 in ?? () from /usr/lib/python3/dist-packages/gi/_gi.cpython-35m-x86_64-linux-gnu.so
#6  0x00005622cf563647 in PyObject_Call ()
#7  0x00005622cf4daee1 in PyEval_EvalFrameEx ()
#8  0x00005622cf4e00df in PyEval_EvalCodeEx ()
#9  0x00005622cf51c5d3 in ?? ()
#10 0x00005622cf563647 in PyObject_Call ()
#11 0x00005622cf51ebfe in ?? ()
#12 0x00005622cf543f2d in _PyObject_GenericGetAttrWithDict ()
#13 0x00005622cf4d6159 in PyEval_EvalFrameEx ()
#14 0x00005622cf4e00df in PyEval_EvalCodeEx ()
#15 0x00005622cf51c648 in ?? ()
#16 0x00005622cf563647 in PyObject_Call ()
#17 0x00005622cf48394e in ?? ()
#18 0x00005622cf563647 in PyObject_Call ()
#19 0x00005622cf516e30 in PyEval_CallObjectWithKeywords ()
#20 0x00007fe34dd4c42c in ?? () from /usr/lib/python3/dist-packages/gi/_gi.cpython-35m-x86_64-linux-gnu.so
#21 0x00007fe34d138e2f in ffi_closure_unix64_inner () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#22 0x00007fe34d1391a0 in ffi_closure_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#23 0x00007fe34d38d6aa in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007fe34d38da60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007fe34d38dd82 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007fe346838d55 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007fe34d139038 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#28 0x00007fe34d138a9a in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#29 0x00007fe34dd4e9cc in ?? () from /usr/lib/python3/dist-packages/gi/_gi.cpython-35m-x86_64-linux-gnu.so
#30 0x00007fe34dd50478 in ?? () from /usr/lib/python3/dist-packages/gi/_gi.cpython-35m-x86_64-linux-gnu.so
#31 0x00005622cf563647 in PyObject_Call ()
#32 0x00005622cf4daee1 in PyEval_EvalFrameEx ()
#33 0x00005622cf4da93f in PyEval_EvalFrameEx ()
#34 0x00005622cf4df286 in ?? ()
#35 0x00005622cf4dff9f in PyEval_EvalCode ()
#36 0x00005622cf5ad8f2 in ?? ()
#37 0x00005622cf5afe1d in PyRun_FileExFlags ()
#38 0x00005622cf5b05be in PyRun_SimpleFileExFlags ()
#39 0x00005622cf5de4d7 in Py_Main ()
#40 0x00005622cf46ec01 in main ()
```

after the records ends, I hit enter -> [00:00]
and tried to move the cursor to the end of the track.
It hung

side note, because my file is 3gpp it goes undetected, so I symlinked it the .mp3 to transcribe it

**Comment by innir** [comment]
Thanks for reporting. It's actually three things you talk about:

> after the records ends, I hit enter -> [00:00]

True, that's how it works now - jumping back to the start after the file ends. I think I'll change it to not insert anything at [00:00.0]

> and tried to move the cursor to the end of the track.
It hung

In the bt you posted ther is nothing abput gtranscibe, only gstreamer, so it might be a problem of the gir?
For me it works, can you tell me the version numbers of all the dependencies listed in https://github.com/innir/gtranscribe/blob/master/README and of your installed gstreamer-1.0* packages?

> side note, because my file is 3gpp it goes undetected, so I symlinked it the .mp3 to transcribe it

.3gpp seems not to be register as an audio MIME type on your system, I can't do anything about it.

**Comment by innir** [comment]
Closing as reporter does not react.
